name: CI

on: pull_request

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
      - name: Install dependencies
        run: yarn bootstrap
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test

  dependabot:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: auto-merge
        uses: ridedott/dependabot-auto-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
